### ISSUE TITLE
can't install on 0.11.13

### ISSUE THREAD

**Issue by zheng1** [mooz/node-icu-charset-detector#15]
```
> node-icu-charset-detector@0.0.7 install /Volumes/data/work/proxy/node_modules/node-icu-charset-detector
> node-gyp rebuild

  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
../node-icu-charset-detector.cpp:66:15: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    New(const v8::Arguments& args) {
              ^~~~~~~~~~~~~
              v8::internal::Arguments
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-icu-charset-detector.cpp:81:19: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    GetName(const v8::Arguments& args) {
                  ^~~~~~~~~~~~~
                  v8::internal::Arguments
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-icu-charset-detector.cpp:93:23: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    GetLanguage(const v8::Arguments& args) {
                      ^~~~~~~~~~~~~
                      v8::internal::Arguments
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-icu-charset-detector.cpp:105:25: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    GetConfidence(const v8::Arguments& args) {
                        ^~~~~~~~~~~~~
                        v8::internal::Arguments
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-icu-charset-detector.cpp:19:25: error: calling a protected constructor of class 'v8::HandleScope'
        v8::HandleScope scope;
                        ^
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node-icu-charset-detector.cpp:22:41: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)'
            = v8::FunctionTemplate::New(CharsetMatch::New);
                                        ^~~~~~~~~~~~~~~~~
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:3520:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../node-icu-charset-detector.cpp:27:67: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at 1st parameter
      ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
        NODE_SET_PROTOTYPE_METHOD(constructorTemplate, "getName", CharsetMatch::GetName);
                                                                  ^~~~~~~~~~~~~~~~~~~~~
/Users/zheng1/.node-gyp/0.11.13/src/node.h:212:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-icu-charset-detector.cpp:28:71: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at 1st parameter
      ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
        NODE_SET_PROTOTYPE_METHOD(constructorTemplate, "getLanguage", CharsetMatch::GetLanguage);
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/zheng1/.node-gyp/0.11.13/src/node.h:212:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-icu-charset-detector.cpp:29:73: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at 1st parameter
      ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
        NODE_SET_PROTOTYPE_METHOD(constructorTemplate, "getConfidence", CharsetMatch::GetConfidence);
                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/zheng1/.node-gyp/0.11.13/src/node.h:212:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-icu-charset-detector.cpp:32:33: error: no member named 'NewSymbol' in 'v8::String'; did you mean 'IsSymbol'?
        target->Set(v8::String::NewSymbol("CharsetMatch"), constructorTemplate->GetFunction());
                    ~~~~~~~~~~~~^~~~~~~~~
                                IsSymbol
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:1441:8: note: 'IsSymbol' declared here
  bool IsSymbol() const;
       ^
../node-icu-charset-detector.cpp:32:33: error: call to non-static member function without an object argument
        target->Set(v8::String::NewSymbol("CharsetMatch"), constructorTemplate->GetFunction());
                    ~~~~~~~~~~~~^~~~~~~~~
../node-icu-charset-detector.cpp:67:17: error: member access into incomplete type 'const v8::internal::Arguments'
        if (args.Length() < 1 || !node::Buffer::HasInstance(args[0]))
                ^
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../node-icu-charset-detector.cpp:68:20: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
            return EXCEPTION(TypeError, "Expected Buffer for the argument");
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node-icu-charset-detector.cpp:11:40: note: expanded from macro 'EXCEPTION'
    ThrowException(v8::Exception::type(v8::String::New(message)))
                                       ^~~~~~~~~~~~
../node-icu-charset-detector.cpp:66:5: note: 'New' declared here
    New(const v8::Arguments& args) {
    ^
../node-icu-charset-detector.cpp:68:41: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of type 'const char [33]'
            return EXCEPTION(TypeError, "Expected Buffer for the argument");
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node-icu-charset-detector.cpp:11:56: note: expanded from macro 'EXCEPTION'
    ThrowException(v8::Exception::type(v8::String::New(message)))
                                                       ^
../node-icu-charset-detector.cpp:66:30: note: passing argument to parameter 'args' here
    New(const v8::Arguments& args) {
                             ^
../node-icu-charset-detector.cpp:71:42: error: type 'const v8::internal::Arguments' does not provide a subscript operator
            CharsetMatch::FromBuffer(args[0]->ToObject())->Wrap(args.This()); // under GC
                                     ~~~~^~
../node-icu-charset-detector.cpp:71:69: error: member access into incomplete type 'const v8::internal::Arguments'
            CharsetMatch::FromBuffer(args[0]->ToObject())->Wrap(args.This()); // under GC
                                                                    ^
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../node-icu-charset-detector.cpp:73:20: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
            return EXCEPTION(Error, errorMessage);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node-icu-charset-detector.cpp:11:40: note: expanded from macro 'EXCEPTION'
    ThrowException(v8::Exception::type(v8::String::New(message)))
                                       ^~~~~~~~~~~~
../node-icu-charset-detector.cpp:66:5: note: 'New' declared here
    New(const v8::Arguments& args) {
    ^
../node-icu-charset-detector.cpp:73:37: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of type 'const char *'
            return EXCEPTION(Error, errorMessage);
                                    ^~~~~~~~~~~~
../node-icu-charset-detector.cpp:11:56: note: expanded from macro 'EXCEPTION'
    ThrowException(v8::Exception::type(v8::String::New(message)))
                                                       ^
../node-icu-charset-detector.cpp:66:30: note: passing argument to parameter 'args' here
    New(const v8::Arguments& args) {
                             ^
../node-icu-charset-detector.cpp:76:20: error: member access into incomplete type 'const v8::internal::Arguments'
        return args.This();
                   ^
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/data/work/proxy/node_modules/node-icu-charset-detector
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
```

**Comment by throrin19** [comment]
i have the same error on node 0.12, have you fixed that or this library is unmaintained ?
